version: '3.8'

services:
  dynamodb-local:
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:2.5.2"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./target/dynamodbdata:/home/dynamodblocal/data"

  api:
    container_name: api
    build: .
    environment: []
    ports:
      - "8080:8080"
